services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pluswerk\PlusMinify\Service\:
    resource: '../Classes/Service/*'
    public: true

  Pluswerk\PlusMinify\EventListener\RenderedEventListener:
    tags:
      - name: event.listener
        identifier: 'Pluswerk\PlusMinify\EventListener\RenderedEventListener'
        event: AUS\SsiInclude\Event\RenderedEvent
