name: Tasks

on: [push, pull_request]

jobs:
  lint-php:
    name: "php: ${{ matrix.php }} TYPO3: ${{ matrix.typo3 }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '82', '83', '84' ]
        typo3: [ '12', '13' ]
    container:
      image: ghcr.io/typo3/core-testing-php${{ matrix.php }}:latest
    steps:
      - name: Install dependencies
        run: apk add --no-cache nodejs
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-composer-
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: composer switchto${{ matrix.typo3 }}
      - run: ./vendor/bin/grumphp run --ansi --no-interaction
      - run: composer test
